version: "0.1" 
services:   
  resgitseruser:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    image: expressmockapp
    ports:
      - "3000:3000"
    stdin_open: true 
  resgitseruserTests:
    build:
      context: ./
      dockerfile: ./test/Dockerfile
    image: expressmockapptests
    ports:
      - "8080:8080"
    stdin_open: true